name: amphitheatre_example
version: 0.0.0+0
description: "Demonstrates how to use the amphitheatre plugin."
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  amphitheatre:
    path: ../

  video_player: ^2.9.2
  image_picker: ^1.1.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
